version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:latest
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: expense_tracker
